### ISSUE TITLE
ondex-mini - Building plugins with new changes fails [sequence.jar]

### ISSUE THREAD

**Issue by AjitPS** [Rothamsted/ondex-knet-builder#3]
Made some changes to the **fasta_gff3 parser** in ondex-knet-builder repo under modules/sequence and tried to take _sequence.jar_ and use it as follows:

1. with existing older Ondex desktop and Ondex-mini installed on Windows and those failed.

2. Testing the new sequence.jar on Linux (by moving it under plugins/ in an existing ondex-mini install) gave the following **error**:
 `Invalid constant pool index 319 in class file net/sourceforge/ondex/export/fasta/Export`
 
3. Assuming it's due to recent ondex-knet-builder Java  8 and Maven assembly plugin (3.3.0 -> 3.3.9) upgrades, I then built the **_ondex-mini_** module in the ondex-knet-builder repo and tested that on both Windows and Linux and got the following **error** on both:
` Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/ondex/WorkflowMain`
`         at net.sourceforge.ondex.OndexMiniMain.main(OndexMiniMain.java:7)`
` Caused by: java.lang.ClassNotFoundException: net.sourceforge.ondex.WorkflowMain`
`         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)`
`         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)`
`         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)`
`         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`
`         ... 1 more `
 
 Note: Other users also report seeing the same error.

**Comment by AjitPS** [comment]
On Linux, tested using `./runme.sh "dir/workflow.xml"`, i.e., via:
` ./runme.sh "testWorkflow_fastaGff3_parser230317/testWorkflow_fastaGff3.xml"`

**Comment by marco-brandizi** [comment]
This is  likely caused by #4 and I'm working on it.

**Comment by marco-brandizi** [comment]
I've fixed #4 and now it should work. Please build ondex/test it again and let me know.

**Comment by AjitPS** [comment]
Thanks @marco-brandizi , it works fine for me now, tested on Linux (lily) by rebuilding ondex-mini and using that.
